### PR TITLE
chore(toml): use correct repo URL

### PR DESCRIPTION
**Pull request by miketheman**
### **Description:**

Noticed that the metadata was not reflective of the source repository.

### **Type of change**:

- [x] Other minor changes (workflow, GitHub configs, etc.)

### **Checklist:**

- [x] All code follows the project's coding style and conventions.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings or errors.

### CODE REVIEW

**Comment by benbenbang** [comment]
Hey @miketheman, thanks for the contribution.

**Comment by benbenbang** [comment]
to pass the check can you please push an empty commit? thanks

**Comment by miketheman** [comment]
Done!

**Review by benbenbang — APPROVED** [review]
👍🏻

**Comment by benbenbang** [comment]
thanks again, merging

**Pull request merged**
